title: Idzan Marko's Blog
description: Idzan Marko's Blog Posts from early 2010's until today
baseurl:
url: "https://markoidzan.com.hr"
permalink: /:title/
markdown: kramdown

pagination:
    enabled: true
    debug: false
    per_page: 5
    premalink: /page:num/
    title: ':title - Page :num'
    limit: 0
    sort_field: 'date'
    sort_reverse: true
  
  plugins:
    - jekyll-seo-tag
    - jekyll-feed
    - jekyll-sitemap
    - jekyll-paginate-v2