title: Idzan Marko's Old Blog
description: Idzan Marko's Old Blog Posts from early 2010's until 2018
baseurl:
url: "https://markoidzan.com.hr"
permalink: /:title/
markdown: kramdown

exclude: [vendor]

pagination:
  enabled: true
  debug: false
  per_page: 10
  premalink: /page:num/
  title: ':title - Page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate-v2